sonar.projectKey=donkey-kong-payments-service
sonar.projectName=Donkey Kong Payments Service

sonar.sources=src
sonar.tests=test

sonar.clojure.file.suffixes=.clj

sonar.clover.reportPath=target/coverage/clover.xml

sonar.sourceEncoding=UTF-8